// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_XU_s5EfydVgwzbY9yY3_Q6k0RtiEQFM',
    appId: '1:984078143510:web:3d080d5abaad46f8bfa537',
    messagingSenderId: '984078143510',
    projectId: 'mercadodasophia-bbd01',
    authDomain: 'mercadodasophia-bbd01.firebaseapp.com',
    storageBucket: 'mercadodasophia-bbd01.firebasestorage.app',
    measurementId: 'G-GM8E5KLTQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_XU_s5EfydVgwzbY9yY3_Q6k0RtiEQFM',
    appId: '1:984078143510:android:80b49c822f8f2d77bfa537',
    messagingSenderId: '984078143510',
    projectId: 'mercadodasophia-bbd01',
    storageBucket: 'mercadodasophia-bbd01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_XU_s5EfydVgwzbY9yY3_Q6k0RtiEQFM',
    appId: '1:984078143510:ios:80b49c822f8f2d77bfa537',
    messagingSenderId: '984078143510',
    projectId: 'mercadodasophia-bbd01',
    storageBucket: 'mercadodasophia-bbd01.firebasestorage.app',
    iosBundleId: 'com.mercadodasophia.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_XU_s5EfydVgwzbY9yY3_Q6k0RtiEQFM',
    appId: '1:984078143510:ios:80b49c822f8f2d77bfa537',
    messagingSenderId: '984078143510',
    projectId: 'mercadodasophia-bbd01',
    storageBucket: 'mercadodasophia-bbd01.firebasestorage.app',
    iosBundleId: 'com.mercadodasophia.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_XU_s5EfydVgwzbY9yY3_Q6k0RtiEQFM',
    appId: '1:984078143510:web:3d080d5abaad46f8bfa537',
    messagingSenderId: '984078143510',
    projectId: 'mercadodasophia-bbd01',
    authDomain: 'mercadodasophia-bbd01.firebaseapp.com',
    storageBucket: 'mercadodasophia-bbd01.firebasestorage.app',
  );
} 